"""Add ocr_task_id to tests

Revision ID: 12e4299f3f81
Revises: dc5a047f9306
Create Date: 2025-09-05 11:21:35.310812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e4299f3f81'
down_revision = 'dc5a047f9306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_task_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('ocr_task_id')

    # ### end Alembic commands ###
