"""add file path columns to tests

Revision ID: 3158fee2a5a9
Revises: 20250926_add_page_review_fks
Create Date: 2025-10-17 07:58:01.261659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3158fee2a5a9'
down_revision = '20250926_add_page_review_fks'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_paper_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rubric_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('marking_guide_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answered_script_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('class_list_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('answered_script_filename')
        batch_op.drop_column('rubric_filename')
        batch_op.drop_column('question_paper_filename')
        batch_op.drop_column('date')
        batch_op.drop_column('combined_scripts_filename')
        batch_op.drop_column('class_list_filename')
        batch_op.drop_column('marking_guide_filename')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marking_guide_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_list_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('question_paper_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rubric_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answered_script_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('combined_scripts_path')
        batch_op.drop_column('class_list_path')
        batch_op.drop_column('answered_script_path')
        batch_op.drop_column('marking_guide_path')
        batch_op.drop_column('rubric_path')
        batch_op.drop_column('question_paper_path')

    # ### end Alembic commands ###
