"""Add ocr_task_id to Test

Revision ID: 8f7191ad32f6
Revises: abaa6a0c26e4
Create Date: 2025-10-18 12:36:13.379641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7191ad32f6'
down_revision = 'abaa6a0c26e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_task_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('ocr_task_id')

    # ### end Alembic commands ###
