"""Add test_id FK to TaskControl

Revision ID: abaa6a0c26e4
Revises: 3158fee2a5a9
Create Date: 2025-10-18 11:29:32.785772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaa6a0c26e4'
down_revision = '3158fee2a5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_control', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('test_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
