"""Switch Test model to store file paths directly

Revision ID: dc5a047f9306
Revises: 2bfaeeb89759
Create Date: 2025-09-04 15:30:36.821976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5a047f9306'
down_revision = '2bfaeeb89759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_paper_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rubric_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('marking_guide_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('answered_script_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('class_list_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_path', sa.String(length=500), nullable=True))
        batch_op.alter_column('exam_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('grade_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('marking_guide_filename')
        batch_op.drop_column('combined_scripts_filename')
        batch_op.drop_column('rubric_filename')
        batch_op.drop_column('question_paper_filename')
        batch_op.drop_column('answered_script_filename')
        batch_op.drop_column('class_list_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_list_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answered_script_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('question_paper_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rubric_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('marking_guide_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('grade_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('exam_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('combined_scripts_path')
        batch_op.drop_column('class_list_path')
        batch_op.drop_column('answered_script_path')
        batch_op.drop_column('marking_guide_path')
        batch_op.drop_column('rubric_path')
        batch_op.drop_column('question_paper_path')

    # ### end Alembic commands ###
